/**
 * @file HeatmapLayer.jsx
 * @description Renders a kernel density heat map overlay on the Leaflet map
 * using the leaflet.heat plugin.
 *
 * This component is mounted inside a <MapContainer> so it has direct access
 * to the Leaflet map instance via the useMap() hook. It dynamically imports
 * leaflet.heat to ensure the plugin attaches to Leaflet after it has fully
 * initialized, preventing race conditions on mount.
 *
 * The heat map visualizes the output of the risk score algorithm as a smooth
 * color gradient across the campus grid:
 *   - Transparent → no risk data
 *   - Green (#22c55e) → low risk
 *   - Amber (#f59e0b) → moderate risk
 *   - Orange (#f97316) → high risk
 *   - Red (#ef4444) → very high risk
 *
 * @param {Array} points - Array of [latitude, longitude, intensity] tuples
 *                         generated by generateHeatmapPoints() in riskScore.js.
 *                         Intensity values range from 0.0 to 1.0.
 */

import { useEffect, useRef } from 'react'
import { useMap } from 'react-leaflet'
import L from 'leaflet'

/**
 * HeatmapLayer component.
 *
 * Renders inside a Leaflet MapContainer and manages the full lifecycle
 * of the heat map layer — creation, update, and cleanup.
 *
 * Re-renders automatically whenever the points array or map instance changes.
 * On each render, the previous heat layer is removed before a new one is
 * created to prevent stacking duplicate layers.
 *
 * Returns null because this component has no visual DOM output of its own —
 * it writes directly to the Leaflet canvas layer.
 *
 * @component
 * @param {Object}   props
 * @param {Array}    props.points - Heat map data points: [[lat, lng, intensity], ...]
 * @returns {null}
 */
export default function HeatmapLayer({ points }) {
  // Access the parent Leaflet map instance provided by react-leaflet context
  const map = useMap()

  // Ref to track the active heat layer so it can be removed on re-render or unmount
  const heatRef = useRef(null)

  useEffect(() => {
    /**
     * Dynamically imports leaflet.heat and renders the heat layer.
     *
     * Dynamic import is used instead of a top-level import to guarantee
     * leaflet.heat attaches to the Leaflet global (window.L) only after
     * Leaflet itself has fully initialized. A top-level import can cause
     * leaflet.heat to run before L.heatLayer is available.
     */
    const loadHeat = async () => {
      await import('leaflet.heat')

      // Remove the previous heat layer before creating a new one
      // Prevents duplicate layers stacking on each re-render
      if (heatRef.current) {
        map.removeLayer(heatRef.current)
        heatRef.current = null
      }

      // Do not render if there are no data points to display
      if (!points || points.length === 0) return

      /**
       * Create and add the heat layer to the map.
       *
       * Configuration:
       *   radius  - Pixel radius of influence per data point (higher = broader blobs)
       *   blur    - Pixel blur applied to each point (higher = smoother transitions)
       *   maxZoom - Zoom level at which points reach maximum intensity
       *   max     - Maximum intensity value in the input data (1.0 = normalized)
       *   gradient - Color stops mapping intensity (0–1) to hex colors
       */
      heatRef.current = L.heatLayer(points, {
        radius: 40,
        blur: 30,
        maxZoom: 17,
        max: 1.0,
        gradient: {
          0.0:  'transparent', // Zero risk — no color rendered
          0.25: '#22c55e',     // Low risk — green
          0.5:  '#f59e0b',     // Moderate risk — amber
          0.75: '#f97316',     // High risk — orange
          1.0:  '#ef4444'      // Very high risk — red
        }
      }).addTo(map)
    }

    loadHeat()

    /**
     * Cleanup function — runs when the component unmounts or before
     * the next effect execution. Removes the heat layer from the map
     * to prevent memory leaks and orphaned canvas elements.
     */
    return () => {
      if (heatRef.current) {
        map.removeLayer(heatRef.current)
        heatRef.current = null
      }
    }
  }, [points, map]) // Re-run when points data or map instance changes

  // This component renders nothing to the DOM directly
  return null
}