/**
 * @file MapView.jsx
 * @description Primary map interface for Guardian Angel.
 *
 * Renders an interactive Leaflet map centered on the UT Austin campus
 * with two data layers that can be toggled independently:
 *
 *   1. Heat Map Layer — a smooth color gradient overlay generated by the
 *      risk score algorithm, showing danger zones across 350 campus grid
 *      points. Updates in real time when the time filter changes.
 *
 *   2. Pin Layer — individual CircleMarker pins for each incident report,
 *      color-coded by category. Verified reports render at full opacity;
 *      pending reports render dimmed. Each pin opens a popup with the
 *      incident details and the computed area risk score.
 *
 * The time-of-day filter bar (All / Morning / Afternoon / Evening / Night)
 * controls both layers simultaneously. Selecting a time slot re-weights
 * the heat map via the temporal relevance matrix in riskScore.js and
 * filters the visible pins to only show reports from that time window.
 *
 * The map defaults to the current real-world time of day on load.
 */

import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from 'react-leaflet'
import { useEffect, useState, useRef } from 'react'
import { supabase } from '../lib/supabase'
import { getLocationRiskScore, getRiskLabel } from '../lib/riskScore'
import L from 'leaflet'
import 'leaflet.heat'
import 'leaflet/dist/leaflet.css'

/** Geographic center of the UT Austin campus (lat, lng) */
const UT_CENTER = [30.2849, -97.7404]

/**
 * Hex color assigned to each incident category.
 * Used for both CircleMarker fills and the legend in the bottom-left corner.
 * @constant {Object.<string, string>}
 */
const CATEGORY_COLORS = {
  poor_lighting: '#FACC15',
  harassment:    '#F97316',
  catcalling:    '#FB923C',
  assault:       '#EF4444',
  theft:         '#8B5CF6',
  unsafe_path:   '#F59E0B',
  feels_unsafe:  '#EC4899',
  other:         '#6B7280',
}

/**
 * Human-readable display labels for each incident category.
 * Used in pin popups and the legend.
 * @constant {Object.<string, string>}
 */
const CATEGORY_LABELS = {
  poor_lighting: 'Poor Lighting',
  harassment:    'Harassment',
  catcalling:    'Catcalling',
  assault:       'Assault',
  theft:         'Theft',
  unsafe_path:   'Unsafe Path',
  feels_unsafe:  'Feels Unsafe',
  other:         'Other',
}

/**
 * Time-of-day filter options displayed in the top pill bar.
 * 'all' falls back to the current real-world time for algorithm purposes.
 * @constant {Array.<{value: string, label: string}>}
 */
const TIME_SLOTS = [
  { value: 'all',       label: 'All' },
  { value: 'morning',   label: '🌅 Morning' },
  { value: 'afternoon', label: '☀️ Afternoon' },
  { value: 'evening',   label: '🌆 Evening' },
  { value: 'night',     label: '🌙 Night' },
]

/**
 * Returns the current time of day bucket based on the system clock.
 * Used to set the default filter on load and as the fallback when
 * the user selects 'all'.
 *
 * @returns {'morning' | 'afternoon' | 'evening' | 'night'}
 */
function getCurrentTimeSlot() {
  const hour = new Date().getHours()
  if (hour >= 6  && hour < 12) return 'morning'
  if (hour >= 12 && hour < 18) return 'afternoon'
  if (hour >= 18 && hour < 22) return 'evening'
  return 'night'
}

// ---------------------------------------------------------------------------
// HEATMAP LAYER
// ---------------------------------------------------------------------------

/**
 * HeatmapLayer — internal Leaflet component rendered inside <MapContainer>.
 *
 * Must be a child of MapContainer to access the Leaflet map instance via
 * useMap(). Generates a grid of risk score points covering the UT Austin
 * campus bounds and passes them to leaflet.heat for rendering.
 *
 * Grid resolution: 0.0010 degrees ≈ 111 meters per step.
 * Only points with a score above the noise threshold (0.05) are included.
 *
 * The layer is fully removed and re-created on every render to prevent
 * stacking duplicate layers when props change.
 *
 * @param {Object}   props
 * @param {Array}    props.reports   - All reports fetched from Supabase
 * @param {string}   props.timeOfDay - Active time filter for the algorithm
 * @param {boolean}  props.enabled   - Whether the heat map is toggled on
 * @returns {null} Renders nothing to the DOM — writes to the Leaflet canvas
 */
function HeatmapLayer({ reports, timeOfDay, enabled }) {
  const map = useMap()

  // Ref holds the active leaflet.heat layer instance for cleanup
  const heatRef = useRef(null)

  useEffect(() => {
    // Remove any existing heat layer before re-rendering
    if (heatRef.current) {
      map.removeLayer(heatRef.current)
      heatRef.current = null
    }

    // Skip rendering if toggled off or no report data exists
    if (!enabled || reports.length === 0) return

    // Campus bounding box — covers UT Austin and surrounding areas
    const GRID = 0.0010
    const BOUNDS = {
      minLat: 30.277, maxLat: 30.294,
      minLng: -97.748, maxLng: -97.730,
    }

    // Generate [lat, lng, intensity] tuples for every grid point on campus
    const points = []
    for (let lat = BOUNDS.minLat; lat <= BOUNDS.maxLat; lat += GRID) {
      for (let lng = BOUNDS.minLng; lng <= BOUNDS.maxLng; lng += GRID) {
        const score = getLocationRiskScore(lat, lng, reports, timeOfDay)
        // Exclude near-zero scores to avoid rendering noise over safe areas
        if (score > 0.05) points.push([lat, lng, score])
      }
    }

    if (points.length === 0) return

    /**
     * Render the heat layer with risk-calibrated color stops.
     *
     * radius  — pixel influence radius per data point
     * blur    — pixel blur for smooth gradient transitions
     * maxZoom — zoom level at which intensity reaches maximum
     * max     — maximum intensity value in the input data (normalized 0–1)
     * gradient — color stops: intensity value → hex color
     */
    heatRef.current = L.heatLayer(points, {
      radius:  45,
      blur:    35,
      maxZoom: 17,
      max:     1.0,
      gradient: {
        0.0:  'transparent', // No risk — no color
        0.25: '#22c55e',     // Low risk — green
        0.5:  '#f59e0b',     // Moderate risk — amber
        0.75: '#f97316',     // High risk — orange
        1.0:  '#ef4444',     // Very high risk — red
      },
    }).addTo(map)

    // Cleanup: remove heat layer on unmount or before next effect run
    return () => {
      if (heatRef.current) {
        map.removeLayer(heatRef.current)
        heatRef.current = null
      }
    }
  }, [reports, timeOfDay, enabled, map])

  return null
}

// ---------------------------------------------------------------------------
// MAPVIEW (main export)
// ---------------------------------------------------------------------------

/**
 * MapView — primary exported component.
 *
 * Fetches all reports from Supabase on mount, manages time filter and
 * layer toggle state, and renders the full map interface including the
 * time filter pill bar, layer toggles, legend, heat map, and pin layer.
 *
 * @component
 * @returns {JSX.Element}
 */
export default function MapView() {
  const [reports,     setReports]     = useState([])
  const [timeFilter,  setTimeFilter]  = useState(getCurrentTimeSlot())
  const [showHeatmap, setShowHeatmap] = useState(true)
  const [showPins,    setShowPins]    = useState(true)

  // Fetch all reports from Supabase on component mount
  useEffect(() => {
    supabase
      .from('reports')
      .select('*')
      .order('created_at', { ascending: false })
      .then(({ data }) => setReports(data || []))
  }, [])

  // When filter is 'all', fall back to the current real-world time
  // so the algorithm still uses a meaningful time window
  const activeTime = timeFilter === 'all' ? getCurrentTimeSlot() : timeFilter

  // Pin layer shows only reports matching the selected time slot
  // Heat map always uses activeTime regardless of this filter
  const filteredReports = timeFilter === 'all'
    ? reports
    : reports.filter(r => r.time_of_day === timeFilter)

  return (
    <div className="relative h-full">

      {/* ── Time filter pill bar ─────────────────────────────────────────── */}
      {/* Floated above the map using absolute positioning + high z-index    */}
      <div style={{ zIndex: 1000, position: 'absolute', top: 16, left: '50%', transform: 'translateX(-50%)' }}>
        <div style={{
          display: 'flex', gap: 2, background: '#0f172a',
          border: '1px solid #334155', borderRadius: 999, padding: 4,
        }}>
          {TIME_SLOTS.map(t => (
            <button
              key={t.value}
              onClick={() => setTimeFilter(t.value)}
              style={{
                padding: '5px 14px', borderRadius: 999, fontSize: 12, fontWeight: 500,
                border: 'none', cursor: 'pointer', transition: 'all 0.15s',
                background: timeFilter === t.value ? '#ec4899' : 'transparent',
                color:      timeFilter === t.value ? '#fff'    : '#94a3b8',
              }}
            >
              {t.label}
            </button>
          ))}
        </div>
      </div>

      {/* ── Layer toggle buttons ─────────────────────────────────────────── */}
      {/* Active state is indicated by colored border and tinted background  */}
      <div style={{ zIndex: 1000, position: 'absolute', top: 70, left: 16, display: 'flex', flexDirection: 'column', gap: 8 }}>
        {/* Toggle heat map overlay */}
        <button onClick={() => setShowHeatmap(v => !v)} style={{
          padding: '7px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer',
          borderRadius: 8, border: `1.5px solid ${showHeatmap ? '#f97316' : '#334155'}`,
          background: showHeatmap ? 'rgba(249,115,22,0.15)' : '#0f172a',
          color: showHeatmap ? '#f97316' : '#64748b', letterSpacing: '0.02em',
        }}>
          {showHeatmap ? 'RISK MAP ON' : 'RISK MAP OFF'}
        </button>

        {/* Toggle individual incident pins */}
        <button onClick={() => setShowPins(v => !v)} style={{
          padding: '7px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer',
          borderRadius: 8, border: `1.5px solid ${showPins ? '#ec4899' : '#334155'}`,
          background: showPins ? 'rgba(236,72,153,0.15)' : '#0f172a',
          color: showPins ? '#ec4899' : '#64748b', letterSpacing: '0.02em',
        }}>
          {showPins ? 'PINS ON' : 'PINS OFF'}
        </button>
      </div>

      {/* ── Legend ───────────────────────────────────────────────────────── */}
      {/* Bottom-left panel showing risk level colors and category colors    */}
      <div style={{
        zIndex: 1000, position: 'absolute', bottom: 32, left: 16,
        background: '#0f172a', border: '1px solid #1e293b',
        borderRadius: 12, padding: '12px 14px', minWidth: 130,
      }}>
        {/* Risk level gradient key */}
        <p style={{ color: '#64748b', fontSize: 11, fontWeight: 600, marginBottom: 8, letterSpacing: '0.05em' }}>
          RISK LEVEL
        </p>
        {[
          { color: '#22c55e', label: 'Low' },
          { color: '#f59e0b', label: 'Moderate' },
          { color: '#f97316', label: 'High' },
          { color: '#ef4444', label: 'Very High' },
        ].map(({ color, label }) => (
          <div key={label} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 6 }}>
            <div style={{ width: 10, height: 10, borderRadius: 2, background: color, flexShrink: 0 }} />
            <span style={{ color: '#cbd5e1', fontSize: 12 }}>{label}</span>
          </div>
        ))}

        {/* Category color key */}
        <div style={{ borderTop: '1px solid #1e293b', marginTop: 8, paddingTop: 8 }}>
          <p style={{ color: '#64748b', fontSize: 11, fontWeight: 600, marginBottom: 6, letterSpacing: '0.05em' }}>
            CATEGORY
          </p>
          {Object.entries(CATEGORY_COLORS).map(([cat, color]) => (
            <div key={cat} style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
              <div style={{ width: 8, height: 8, borderRadius: '50%', background: color, flexShrink: 0 }} />
              <span style={{ color: '#94a3b8', fontSize: 11, textTransform: 'capitalize' }}>
                {cat.replace('_', ' ')}
              </span>
            </div>
          ))}
        </div>
      </div>

      {/* ── Leaflet Map ───────────────────────────────────────────────────── */}
      <MapContainer
        center={UT_CENTER}
        zoom={15}
        style={{ height: '100%', width: '100%' }}
      >
        {/* Base tile layer — free OpenStreetMap tiles, no API key required */}
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; OpenStreetMap contributors'
        />

        {/* Heat map overlay — powered by the risk score algorithm */}
        <HeatmapLayer
          reports={reports}
          timeOfDay={activeTime}
          enabled={showHeatmap}
        />

        {/* Individual incident pins — only rendered when showPins is true */}
        {showPins && filteredReports.map(r => {
          // Compute area risk score for this pin's location
          const score = getLocationRiskScore(r.lat, r.lng, reports, activeTime)
          const risk  = getRiskLabel(score)

          return (
            <CircleMarker
              key={r.id}
              center={[r.lat, r.lng]}
              radius={7}
              pathOptions={{
                color:       CATEGORY_COLORS[r.category] || '#6B7280',
                fillColor:   CATEGORY_COLORS[r.category] || '#6B7280',
                // Verified reports render at full opacity; pending reports are dimmed
                fillOpacity: r.status === 'verified' ? 0.9 : 0.4,
                weight: 2,
              }}
            >
              {/* Popup shown on pin click */}
              <Popup>
                <div style={{ minWidth: 190 }}>
                  {/* Category name and risk level badge */}
                  <strong style={{ textTransform: 'capitalize' }}>
                    {CATEGORY_LABELS[r.category] || r.category}
                  </strong>
                  <span style={{
                    marginLeft: 6, background: risk.color + '33',
                    color: risk.color, fontSize: 10,
                    padding: '1px 6px', borderRadius: 4, fontWeight: 600,
                  }}>
                    {risk.label}
                  </span>

                  {/* Time of day indicator */}
                  {r.time_of_day && (
                    <p style={{ fontSize: 11, color: '#888', margin: '3px 0' }}>
                      {r.time_of_day === 'morning'   && '🌅 Morning'}
                      {r.time_of_day === 'afternoon' && '☀️ Afternoon'}
                      {r.time_of_day === 'evening'   && '🌆 Evening'}
                      {r.time_of_day === 'night'     && '🌙 Night'}
                    </p>
                  )}

                  {/* Incident description (anonymous — no user identity shown) */}
                  <p style={{ fontSize: 12, margin: '4px 0' }}>{r.description}</p>

                  {/* Community credibility score and verification status */}
                  <div style={{ fontSize: 11, color: '#888' }}>
                    Credibility: {r.credibility_score}/100
                    {r.status === 'verified' ? ' ✓ Verified' : ' (pending)'}
                  </div>

                  {/* Computed area risk score from the algorithm */}
                  <div style={{
                    marginTop: 6, padding: '4px 8px',
                    background: '#f8f8f8', borderRadius: 6,
                    fontSize: 11, color: '#555',
                  }}>
                    Area risk score: {Math.round(score * 100)}/100
                  </div>
                </div>
              </Popup>
            </CircleMarker>
          )
        })}
      </MapContainer>
    </div>
  )
}